export const NATIONS: Record<Nation, { name: Nation; warWith: Nation }> = {
  England: {
    name: "England",
    warWith: "France",
  },
  France: {
    name: "France",
    warWith: "England",
  },
  Spain: {
    name: "Spain",
    warWith: "Holland",
  },
  Holland: {
    name: "Holland",
    warWith: "Spain",
  },
}

export const LOCATIONS = {
  shop: "Shop",
  tavern: "Tavern",
  bank: "Bank",
  market: "Market",
  shipyard: "Shipyard",
  cityhall: "City hall",
  harbor: "Harbor",
  sea: "Sea",
} as Record<string, TownLocation | SeaLocation>

export type TownLocations = Record<
  Town,
  {
    nation: Nation
    descriptions?: Partial<Record<TownLocation | SeaLocation, string>>
    map: {
      x: number
      y: number
      textAlign?: "bottom" | "right"
      distanceTo: Record<Town, number>
    }
  }
>

const DISTSANCES = {
  CHARLES_TOWNE_BILOXI: 5,
  CHARLES_TOWNE_HAVANA: 2,
  CHARLES_TOWNE_BELIZE: 5,
  CHARLES_TOWNE_VILLA_HERMOSA: 6,
  CHARLES_TOWNE_PORT_ROYALE: 5,
  CHARLES_TOWNE_LEOGANE: 4,
  CHARLES_TOWNE_TORTUGA: 4,
  CHARLES_TOWNE_SAN_JUAN: 5,
  CHARLES_TOWNE_ST_MARTIN: 5,
  CHARLES_TOWNE_ST_EUSTATIUS: 5,
  CHARLES_TOWNE_MARTINIQUE: 6,
  CHARLES_TOWNE_BARBADOS: 7,
  CHARLES_TOWNE_BONAIRE: 6,
  CHARLES_TOWNE_CURACAO: 5,
  CHARLES_TOWNE_PANAMA: 6,
  BARBADOS_MARTINIQUE: 1,
  BARBADOS_ST_EUSTATIUS: 1,
  BARBADOS_ST_MARTIN: 2,
  BARBADOS_SAN_JUAN: 2,
  BARBADOS_TORTUGA: 3,
  BARBADOS_LEOGANE: 3,
  BARBADOS_PORT_ROYALE: 4,
  BARBADOS_HAVANA: 5,
  BARBADOS_BONAIRE: 2,
  BARBADOS_CURACAO: 3,
  BARBADOS_PANAMA: 5,
  BARBADOS_BELIZE: 7,
  BARBADOS_BILOXI: 8,
  BARBADOS_VILLA_HERMOSA: 9,
  BARBADOS_CHARLES_TOWNE: 6,
  PORT_ROYALE_HAVANA: 2,
  PORT_ROYALE_LEOGANE: 1,
  PORT_ROYALE_TORTUGA: 2,
  PORT_ROYALE_SAN_JUAN: 3,
  PORT_ROYALE_ST_MARTIN: 3,
  PORT_ROYALE_ST_EUSTATIUS: 3,
  PORT_ROYALE_MARTINIQUE: 3,
  PORT_ROYALE_BARBADOS: 4,
  PORT_ROYALE_BONAIRE: 3,
  PORT_ROYALE_CURACAO: 2,
  PORT_ROYALE_PANAMA: 2,
  PORT_ROYALE_BELIZE: 3,
  PORT_ROYALE_VILLA_HERMOSA: 5,
  PORT_ROYALE_BILOXI: 5,
  BELIZE_VILLA_HERMOSA: 4,
  BELIZE_HAVANA: 2,
  BELIZE_BILOXI: 4,
  BELIZE_CHARLES_TOWNE: 5,
  BELIZE_PANAMA: 3,
  BELIZE_CURACAO: 5,
  BELIZE_BONAIRE: 5,
  BELIZE_BARBADOS: 7,
  BELIZE_MARTINIQUE: 6,
  BELIZE_ST_EUSTATIUS: 6,
  BELIZE_ST_MARTIN: 6,
  BELIZE_SAN_JUAN: 6,
  BELIZE_TORTUGA: 5,
  BELIZE_LEOGANE: 4,
  BELIZE_PORT_ROYALE: 3,
  TORTUGA_LEOGANE: 1,
  TORTUGA_SAN_JUAN: 1,
  TORTUGA_PORT_ROYALE: 2,
  TORTUGA_ST_MARTIN: 2,
  TORTUGA_ST_EUSTATIUS: 2,
  TORTUGA_MARTINIQUE: 3,
  TORTUGA_BARBADOS: 3,
  TORTUGA_BONAIRE: 3,
  TORTUGA_CURACAO: 3,
  TORTUGA_PANAMA: 5,
  TORTUGA_BELIZE: 5,
  TORTUGA_VILLA_HERMOSA: 7,
  TORTUGA_BILOXI: 5,
  TORTUGA_CHARLES_TOWNE: 4,
  TORTUGA_HAVANA: 3,
  LEOGANE_PORT_ROYALE: 1,
  LEOGANE_TORTUGA: 1,
  LEOGANE_SAN_JUAN: 2,
  LEOGANE_ST_MARTIN: 2,
  LEOGANE_ST_EUSTATIUS: 3,
  LEOGANE_MARTINIQUE: 3,
  LEOGANE_BARBADOS: 3,
  LEOGANE_BILOXI: 5,
  LEOGANE_BONAIRE: 3,
  LEOGANE_CURACAO: 3,
  LEOGANE_PANAMA: 3,
  LEOGANE_HAVANA: 4,
  LEOGANE_BELIZE: 4,
  LEOGANE_VILLA_HERMOSA: 7,
  MARTINIQUE_ST_EUSTATIUS: 1,
  MARTINIQUE_ST_MARTIN: 1,
  MARTINIQUE_SAN_JUAN: 2,
  MARTINIQUE_HAVANA: 6,
  MARTINIQUE_BONAIRE: 3,
  MARTINIQUE_CURACAO: 3,
  MARTINIQUE_PANAMA: 5,
  MARTINIQUE_VILLA_HERMOSA: 9,
  MARTINIQUE_BILOXI: 8,
  BILOXI_HAVANA: 2,
  BILOXI_VILLA_HERMOSA: 3,
  BILOXI_PANAMA: 5,
  BILOXI_CURACAO: 6,
  BILOXI_BONAIRE: 7,
  BILOXI_ST_EUSTATIUS: 8,
  BILOXI_ST_MARTIN: 8,
  BILOXI_SAN_JUAN: 8,
  PANAMA_CURACAO: 2,
  PANAMA_BONAIRE: 3,
  PANAMA_VILLA_HERMOSA: 6,
  PANAMA_HAVANA: 4,
  PANAMA_SAN_JUAN: 4,
  PANAMA_ST_MARTIN: 5,
  PANAMA_ST_EUSTATIUS: 5,
  HAVANA_VILLA_HERMOSA: 4,
  HAVANA_CURACAO: 4,
  HAVANA_BONAIRE: 5,
  HAVANA_ST_EUSTATIUS: 6,
  HAVANA_ST_MARTIN: 5,
  HAVANA_SAN_JUAN: 4,
  VILLA_HERMOSA_CURACAO: 6,
  VILLA_HERMOSA_BONAIRE: 7,
  VILLA_HERMOSA_ST_EUSTATIUS: 7,
  VILLA_HERMOSA_ST_MARTIN: 7,
  VILLA_HERMOSA_SAN_JUAN: 7,
  SAN_JUAN_ST_MARTIN: 1,
  SAN_JUAN_ST_EUSTATIUS: 1,
  SAN_JUAN_CURACAO: 2,
  SAN_JUAN_BONAIRE: 2,
  BONAIRE_CURACAO: 1,
  BONAIRE_ST_EUSTATIUS: 2,
  BONAIRE_ST_MARTIN: 2,
  CURACAO_ST_EUSTATIUS: 3,
  CURACAO_ST_MARTIN: 3,
  ST_MARTIN_ST_EUSTATIUS: 1,
}

export const TOWNS: TownLocations = {
  "Charles Towne": {
    nation: "England",
    descriptions: {
      Shop: "Amidst the lively town square, The Maritime Emporium allures passersby with its diverse wares, offering nourishing provisions, canteens of pure water, medicinal remedies, fine tobacco, aged rum, delicate porcelain, and an exotic assortment of aromatic spices, evoking the spirit of maritime adventure and worldly trade.",
      Tavern:
        "Amidst the cobbled streets, The Salty Seadog Tavern exudes a rustic charm, where wine, tobacco, and rum flow freely, and the lively chatter of talkative pirates fills the air with tales of daring escapades.",
    },
    map: {
      x: 388,
      y: 47,
      textAlign: "bottom",
      distanceTo: {
        "Charles Towne": 0,
        Biloxi: DISTSANCES.CHARLES_TOWNE_BILOXI,
        Havana: DISTSANCES.CHARLES_TOWNE_HAVANA,
        Belize: DISTSANCES.CHARLES_TOWNE_BELIZE,
        "Villa Hermosa": DISTSANCES.CHARLES_TOWNE_VILLA_HERMOSA,
        "Port Royale": DISTSANCES.CHARLES_TOWNE_PORT_ROYALE,
        Leogane: DISTSANCES.CHARLES_TOWNE_LEOGANE,
        Tortuga: DISTSANCES.CHARLES_TOWNE_TORTUGA,
        "San Juan": DISTSANCES.CHARLES_TOWNE_SAN_JUAN,
        "St. Martin": DISTSANCES.CHARLES_TOWNE_ST_MARTIN,
        "St. Eustatius": DISTSANCES.CHARLES_TOWNE_ST_EUSTATIUS,
        Martinique: DISTSANCES.CHARLES_TOWNE_MARTINIQUE,
        Barbados: DISTSANCES.CHARLES_TOWNE_BARBADOS,
        Bonaire: DISTSANCES.CHARLES_TOWNE_BONAIRE,
        Curacao: DISTSANCES.CHARLES_TOWNE_CURACAO,
        Panama: DISTSANCES.CHARLES_TOWNE_PANAMA,
      },
    },
  },
  Barbados: {
    nation: "England",
    descriptions: {
      Shop: "Within the bustling market square, The Captain's Cove Emporium beckons with a rich assortment of provisions, leather-bound water bottles, healing tonics, aromatic tobacco, aged rum, delicate porcelain, and a tantalizing array of spices, evoking the essence of maritime exploration and exotic trade.",
      Tavern:
        "Nestled in the heart of the town, The Captain's Quarters Inn entices patrons with its rich libations of wine, tobacco, and rum, while talkative pirates spin riveting yarns that whisk listeners away to the high seas.",
    },
    map: {
      x: 779,
      y: 387,
      distanceTo: {
        Barbados: 0,
        Martinique: DISTSANCES.BARBADOS_MARTINIQUE,
        "St. Eustatius": DISTSANCES.BARBADOS_ST_EUSTATIUS,
        "St. Martin": DISTSANCES.BARBADOS_ST_MARTIN,
        "San Juan": DISTSANCES.BARBADOS_SAN_JUAN,
        Tortuga: DISTSANCES.BARBADOS_TORTUGA,
        Leogane: DISTSANCES.BARBADOS_LEOGANE,
        "Port Royale": DISTSANCES.BARBADOS_PORT_ROYALE,
        Havana: DISTSANCES.BARBADOS_HAVANA,
        Bonaire: DISTSANCES.BARBADOS_BONAIRE,
        Curacao: DISTSANCES.BARBADOS_CURACAO,
        Panama: DISTSANCES.BARBADOS_PANAMA,
        Belize: DISTSANCES.BARBADOS_BELIZE,
        "Villa Hermosa": DISTSANCES.BARBADOS_VILLA_HERMOSA,
        Biloxi: DISTSANCES.BARBADOS_BILOXI,
        "Charles Towne": DISTSANCES.BARBADOS_CHARLES_TOWNE,
      },
    },
  },
  "Port Royale": {
    nation: "England",
    descriptions: {
      Shop: "Nestled along the lively quayside, The Seafarer's Emporium entices with its treasure trove of sustenance, leather-clad water flasks, healing elixirs, aromatic tobacco, aged rum, delicate porcelain, and an exotic array of spices, embodying the spirit of maritime adventure and alluring trade.",
      Tavern:
        "Within the lively tavern known as The Buccaneer's Cove, the air is thick with the aroma of wine, tobacco, and rum, as talkative pirates gather to swap stories of their adventurous exploits.",
    },
    map: {
      x: 452,
      y: 306,
      distanceTo: {
        "Port Royale": 0,
        Havana: DISTSANCES.PORT_ROYALE_HAVANA,
        Leogane: DISTSANCES.PORT_ROYALE_LEOGANE,
        Tortuga: DISTSANCES.PORT_ROYALE_TORTUGA,
        "San Juan": DISTSANCES.PORT_ROYALE_SAN_JUAN,
        "St. Martin": DISTSANCES.PORT_ROYALE_ST_MARTIN,
        "St. Eustatius": DISTSANCES.PORT_ROYALE_ST_EUSTATIUS,
        Martinique: DISTSANCES.PORT_ROYALE_MARTINIQUE,
        Barbados: DISTSANCES.PORT_ROYALE_BARBADOS,
        Bonaire: DISTSANCES.PORT_ROYALE_BONAIRE,
        Curacao: DISTSANCES.PORT_ROYALE_CURACAO,
        Panama: DISTSANCES.PORT_ROYALE_PANAMA,
        Belize: DISTSANCES.PORT_ROYALE_BELIZE,
        "Villa Hermosa": DISTSANCES.PORT_ROYALE_VILLA_HERMOSA,
        Biloxi: DISTSANCES.PORT_ROYALE_BILOXI,
        "Charles Towne": DISTSANCES.CHARLES_TOWNE_PORT_ROYALE,
      },
    },
  },
  Belize: {
    nation: "England",
    descriptions: {
      Shop: "Amidst the cobblestone streets, The Adventurer's Emporium beckons with its diverse offerings, from nourishing victuals and leather-bound water bottles to medicinal tinctures, aromatic tobacco, aged rum, delicate porcelain, and an exotic assortment of spices, all evoking the allure of daring expeditions and global trade.",
      Tavern:
        "Amidst the bustling town square, The Shipwrecked Sailor Alehouse beckons with its offerings of wine, tobacco, and rum, as talkative pirates recount their daring escapades over merry glasses.",
    },
    map: {
      x: 207,
      y: 303,
      textAlign: "right",
      distanceTo: {
        Belize: 0,
        "Villa Hermosa": DISTSANCES.BELIZE_VILLA_HERMOSA,
        Havana: DISTSANCES.BELIZE_HAVANA,
        Biloxi: DISTSANCES.BELIZE_BILOXI,
        "Charles Towne": DISTSANCES.BELIZE_CHARLES_TOWNE,
        Panama: DISTSANCES.BELIZE_PANAMA,
        Curacao: DISTSANCES.BELIZE_CURACAO,
        Bonaire: DISTSANCES.BELIZE_BONAIRE,
        Barbados: DISTSANCES.BELIZE_BARBADOS,
        Martinique: DISTSANCES.BELIZE_MARTINIQUE,
        "St. Eustatius": DISTSANCES.BELIZE_ST_EUSTATIUS,
        "St. Martin": DISTSANCES.BELIZE_ST_MARTIN,
        "San Juan": DISTSANCES.BELIZE_SAN_JUAN,
        Tortuga: DISTSANCES.BELIZE_TORTUGA,
        Leogane: DISTSANCES.BELIZE_LEOGANE,
        "Port Royale": DISTSANCES.BELIZE_PORT_ROYALE,
      },
    },
  },
  Tortuga: {
    nation: "France",
    descriptions: {
      Shop: "Within the old town's bustling center, The Maritime Emporium lures in passersby with its eclectic range of goods, from nourishing provisions and leather-clad water bottles to medicinal remedies, aromatic tobacco, aged rum, delicate porcelain, and a captivating variety of spices, invoking a sense of seafaring adventure and worldly intrigue.",
      Tavern:
        "The Jolly Roger Inn stands tall, a cozy tavern where wine, tobacco, and rum flow freely, and talkative pirates share their legendary tales with eager ears.",
    },
    map: {
      x: 598,
      y: 262,
      distanceTo: {
        Tortuga: 0,
        Leogane: DISTSANCES.TORTUGA_LEOGANE,
        "San Juan": DISTSANCES.TORTUGA_SAN_JUAN,
        "Port Royale": DISTSANCES.TORTUGA_PORT_ROYALE,
        "St. Martin": DISTSANCES.TORTUGA_ST_MARTIN,
        "St. Eustatius": DISTSANCES.TORTUGA_ST_EUSTATIUS,
        Martinique: DISTSANCES.TORTUGA_MARTINIQUE,
        Barbados: DISTSANCES.TORTUGA_BARBADOS,
        Bonaire: DISTSANCES.TORTUGA_BONAIRE,
        Curacao: DISTSANCES.TORTUGA_CURACAO,
        Panama: DISTSANCES.TORTUGA_PANAMA,
        Belize: DISTSANCES.TORTUGA_BELIZE,
        "Villa Hermosa": DISTSANCES.TORTUGA_VILLA_HERMOSA,
        Biloxi: DISTSANCES.TORTUGA_BILOXI,
        "Charles Towne": DISTSANCES.TORTUGA_CHARLES_TOWNE,
        Havana: DISTSANCES.TORTUGA_HAVANA,
      },
    },
  },
  Leogane: {
    nation: "France",
    descriptions: {
      Shop: "In the heart of the old town, The Seafarer's Emporium entices with its diverse selection, from nourishing provisions and leather-clad water bottles to healing elixirs, aromatic tobacco, aged rum, delicate porcelain, and an enchanting array of spices, evoking the charm of maritime exploration and international trade.",
      Tavern:
        "Tucked away in the narrow alleys, The Sea Serpent's Hideaway lures with its enticing wines, tobacco, and rum, and the laughter of talkative pirates fills the air.",
    },
    map: {
      x: 537,
      y: 300,
      distanceTo: {
        Leogane: 0,
        "Port Royale": DISTSANCES.LEOGANE_PORT_ROYALE,
        Tortuga: DISTSANCES.LEOGANE_TORTUGA,
        "San Juan": DISTSANCES.LEOGANE_SAN_JUAN,
        "St. Martin": DISTSANCES.LEOGANE_ST_MARTIN,
        "St. Eustatius": DISTSANCES.LEOGANE_ST_EUSTATIUS,
        Martinique: DISTSANCES.LEOGANE_MARTINIQUE,
        Barbados: DISTSANCES.LEOGANE_BARBADOS,
        Bonaire: DISTSANCES.LEOGANE_BONAIRE,
        Curacao: DISTSANCES.LEOGANE_CURACAO,
        Panama: DISTSANCES.LEOGANE_PANAMA,
        Belize: DISTSANCES.LEOGANE_BELIZE,
        "Villa Hermosa": DISTSANCES.LEOGANE_VILLA_HERMOSA,
        Biloxi: DISTSANCES.LEOGANE_BILOXI,
        "Charles Towne": DISTSANCES.CHARLES_TOWNE_LEOGANE,
        Havana: DISTSANCES.LEOGANE_HAVANA,
      },
    },
  },
  Martinique: {
    nation: "France",
    descriptions: {
      Shop: "Amidst the bustling market square, The Adventurer's Emporium calls out with its captivating offerings, encompassing nourishing victuals and leather-bound water bottles, medicinal tinctures, aromatic tobacco, aged rum, delicate porcelain, and an exotic assortment of spices, all conjuring visions of daring expeditions and global commerce.",
      Tavern:
        "Along the waterfront, The Smuggler's Den Tavern serves up wine, tobacco, and rum to a boisterous crowd of talkative pirates, swapping tales that captivate everyone present.",
    },
    map: {
      x: 752,
      y: 353,
      textAlign: "right",
      distanceTo: {
        Martinique: 0,
        "St. Eustatius": DISTSANCES.MARTINIQUE_ST_EUSTATIUS,
        "St. Martin": DISTSANCES.MARTINIQUE_ST_MARTIN,
        "San Juan": DISTSANCES.MARTINIQUE_SAN_JUAN,
        Barbados: DISTSANCES.BARBADOS_MARTINIQUE,
        Tortuga: DISTSANCES.TORTUGA_MARTINIQUE,
        Leogane: DISTSANCES.LEOGANE_MARTINIQUE,
        "Port Royale": DISTSANCES.PORT_ROYALE_MARTINIQUE,
        Havana: DISTSANCES.MARTINIQUE_HAVANA,
        Bonaire: DISTSANCES.MARTINIQUE_BONAIRE,
        Curacao: DISTSANCES.MARTINIQUE_CURACAO,
        Panama: DISTSANCES.MARTINIQUE_PANAMA,
        Belize: DISTSANCES.BELIZE_MARTINIQUE,
        "Villa Hermosa": DISTSANCES.MARTINIQUE_VILLA_HERMOSA,
        Biloxi: DISTSANCES.MARTINIQUE_BILOXI,
        "Charles Towne": DISTSANCES.CHARLES_TOWNE_MARTINIQUE,
      },
    },
  },
  Biloxi: {
    nation: "France",
    descriptions: {
      Shop: "Nestled along the cobblestone streets, The Maritime Emporium allures with its treasure trove, housing nourishing victuals and leather-clad water bottles, medicinal remedies, aromatic tobacco, aged rum, delicate porcelain, and a captivating variety of spices, embodying the spirit of seafaring adventures and exotic trade.",
      Tavern:
        "In the heart of the town's nightlife, The Blackbeard's Lair entices with its selection of wine, tobacco, and rum, while talkative pirates regale one another with thrilling stories.",
    },
    map: {
      x: 259,
      y: 68,
      distanceTo: {
        Biloxi: 0,
        "Charles Towne": DISTSANCES.CHARLES_TOWNE_BILOXI,
        Havana: DISTSANCES.BILOXI_HAVANA,
        Belize: DISTSANCES.BELIZE_BILOXI,
        "Villa Hermosa": DISTSANCES.BILOXI_VILLA_HERMOSA,
        Panama: DISTSANCES.BILOXI_PANAMA,
        Curacao: DISTSANCES.BILOXI_CURACAO,
        Bonaire: DISTSANCES.BILOXI_BONAIRE,
        Barbados: DISTSANCES.BARBADOS_BILOXI,
        Martinique: DISTSANCES.MARTINIQUE_BILOXI,
        "St. Eustatius": DISTSANCES.BILOXI_ST_EUSTATIUS,
        "St. Martin": DISTSANCES.BILOXI_ST_MARTIN,
        "San Juan": DISTSANCES.BILOXI_SAN_JUAN,
        Tortuga: DISTSANCES.TORTUGA_BELIZE,
        Leogane: DISTSANCES.LEOGANE_BELIZE,
        "Port Royale": DISTSANCES.PORT_ROYALE_BELIZE,
      },
    },
  },
  Panama: {
    nation: "Spain",
    descriptions: {
      Shop: "Nestled along the cobblestone streets, The Maritime Emporium allures with its treasure trove, housing nourishing victuals and leather-clad water bottles, medicinal remedies, aromatic tobacco, aged rum, delicate porcelain, and a captivating variety of spices, embodying the spirit of seafaring adventures and exotic trade.",
      Tavern:
        "The Pirate's Cove Tavern exudes a seafaring charm, where wine, tobacco, and rum are readily available, and talkative pirates entertain with tales of daring adventures on the high seas.",
    },
    map: {
      x: 382,
      y: 459,
      distanceTo: {
        Panama: 0,
        Curacao: DISTSANCES.PANAMA_CURACAO,
        Bonaire: DISTSANCES.PANAMA_BONAIRE,
        Belize: DISTSANCES.BELIZE_PANAMA,
        "Villa Hermosa": DISTSANCES.PANAMA_VILLA_HERMOSA,
        Biloxi: DISTSANCES.BILOXI_PANAMA,
        "Charles Towne": DISTSANCES.CHARLES_TOWNE_PANAMA,
        Havana: DISTSANCES.PANAMA_HAVANA,
        Tortuga: DISTSANCES.TORTUGA_PANAMA,
        Leogane: DISTSANCES.LEOGANE_PANAMA,
        "Port Royale": DISTSANCES.PORT_ROYALE_PANAMA,
        "San Juan": DISTSANCES.PANAMA_SAN_JUAN,
        "St. Martin": DISTSANCES.PANAMA_ST_MARTIN,
        "St. Eustatius": DISTSANCES.PANAMA_ST_EUSTATIUS,
        Martinique: DISTSANCES.MARTINIQUE_PANAMA,
        Barbados: DISTSANCES.BARBADOS_PANAMA,
      },
    },
  },
  Havana: {
    nation: "Spain",
    descriptions: {
      Shop: "Within the town's lively center, The Wandering Merchant beckons with its diverse stock, ranging from nourishing victuals and leather-bound water bottles to healing tonics, fragrant tobacco, aged rum, delicate porcelain, and a tantalizing array of spices, invoking the essence of adventurous journeys and cultural exchange.",
      Tavern:
        "Nestled within the old town's narrow lanes, The Mariner's Retreat beckons with its offerings of wine, tobacco, and rum, as talkative pirates share their escapades, weaving an atmosphere of excitement and merriment.",
    },
    map: {
      x: 351,
      y: 204,
      distanceTo: {
        Havana: 0,
        Biloxi: DISTSANCES.BILOXI_HAVANA,
        "Charles Towne": DISTSANCES.CHARLES_TOWNE_HAVANA,
        Belize: DISTSANCES.BELIZE_HAVANA,
        "Villa Hermosa": DISTSANCES.HAVANA_VILLA_HERMOSA,
        Panama: DISTSANCES.PANAMA_HAVANA,
        Curacao: DISTSANCES.HAVANA_CURACAO,
        Bonaire: DISTSANCES.HAVANA_BONAIRE,
        Barbados: DISTSANCES.BARBADOS_HAVANA,
        Martinique: DISTSANCES.MARTINIQUE_HAVANA,
        "St. Eustatius": DISTSANCES.HAVANA_ST_EUSTATIUS,
        "St. Martin": DISTSANCES.HAVANA_ST_MARTIN,
        "San Juan": DISTSANCES.HAVANA_SAN_JUAN,
        Tortuga: DISTSANCES.TORTUGA_HAVANA,
        Leogane: DISTSANCES.LEOGANE_HAVANA,
        "Port Royale": DISTSANCES.PORT_ROYALE_HAVANA,
      },
    },
  },
  "Villa Hermosa": {
    nation: "Spain",
    descriptions: {
      Shop: "In the heart of the quaint town square, The Trader's Emporium enchants patrons with its alluring assortment, featuring nourishing provisions and leather-clad water bottles, medicinal elixirs, aromatic tobacco, aged rum, delicate porcelain, and an exotic blend of spices, evoking the spirit of exploration and intercontinental trade.",
      Tavern:
        "The Swashbuckler's Hideout entices patrons with its choice wines, tobacco, and rum, where talkative pirates fill the air with captivating tales of their high-sea exploits.",
    },
    map: {
      x: 133,
      y: 303,
      distanceTo: {
        "Villa Hermosa": 0,
        Belize: DISTSANCES.BELIZE_VILLA_HERMOSA,
        "Charles Towne": DISTSANCES.CHARLES_TOWNE_VILLA_HERMOSA,
        Biloxi: DISTSANCES.BILOXI_VILLA_HERMOSA,
        Havana: DISTSANCES.HAVANA_VILLA_HERMOSA,
        Panama: DISTSANCES.PANAMA_VILLA_HERMOSA,
        Curacao: DISTSANCES.VILLA_HERMOSA_CURACAO,
        Bonaire: DISTSANCES.VILLA_HERMOSA_BONAIRE,
        Barbados: DISTSANCES.BARBADOS_VILLA_HERMOSA,
        Martinique: DISTSANCES.MARTINIQUE_VILLA_HERMOSA,
        "St. Eustatius": DISTSANCES.VILLA_HERMOSA_ST_EUSTATIUS,
        "St. Martin": DISTSANCES.VILLA_HERMOSA_ST_MARTIN,
        "San Juan": DISTSANCES.VILLA_HERMOSA_SAN_JUAN,
        Tortuga: DISTSANCES.TORTUGA_VILLA_HERMOSA,
        Leogane: DISTSANCES.LEOGANE_VILLA_HERMOSA,
        "Port Royale": DISTSANCES.PORT_ROYALE_VILLA_HERMOSA,
      },
    },
  },
  "San Juan": {
    nation: "Spain",
    descriptions: {
      Shop: "Amidst the bustling streets, The Globe-Trotter's Emporium entices with its rich collection, including nourishing victuals and leather-bound water bottles, medicinal concoctions, fragrant tobacco, aged rum, delicate porcelain, and an enticing array of spices, evoking a sense of adventurous voyages and cosmopolitan commerce.",
      Tavern:
        "Within the cozy tavern known as The Rumrunner's Haven, wine, tobacco, and rum flow aplenty, while talkative pirates regale eager listeners with stories of their daring adventures.",
    },
    map: {
      x: 661,
      y: 283,
      distanceTo: {
        "San Juan": 0,
        "St. Martin": DISTSANCES.SAN_JUAN_ST_MARTIN,
        "St. Eustatius": DISTSANCES.SAN_JUAN_ST_EUSTATIUS,
        Martinique: DISTSANCES.MARTINIQUE_SAN_JUAN,
        Barbados: DISTSANCES.BARBADOS_SAN_JUAN,
        Tortuga: DISTSANCES.TORTUGA_SAN_JUAN,
        Leogane: DISTSANCES.LEOGANE_SAN_JUAN,
        "Port Royale": DISTSANCES.PORT_ROYALE_SAN_JUAN,
        Biloxi: DISTSANCES.BILOXI_SAN_JUAN,
        "Charles Towne": DISTSANCES.CHARLES_TOWNE_SAN_JUAN,
        Havana: DISTSANCES.HAVANA_SAN_JUAN,
        Belize: DISTSANCES.BELIZE_SAN_JUAN,
        "Villa Hermosa": DISTSANCES.VILLA_HERMOSA_SAN_JUAN,
        Panama: DISTSANCES.PANAMA_SAN_JUAN,
        Curacao: DISTSANCES.SAN_JUAN_CURACAO,
        Bonaire: DISTSANCES.SAN_JUAN_BONAIRE,
      },
    },
  },
  Bonaire: {
    nation: "Holland",
    descriptions: {
      Shop: "Nestled along the historic quayside, The Traveler's Bazaar enthralls visitors with its diverse treasure trove, encompassing nourishing provisions and leather-clad water bottles, medicinal tonics, aromatic tobacco, aged rum, delicate porcelain, and a captivating mix of spices, embodying the allure of maritime adventures and international markets.",
      Tavern:
        "Nestled amidst the town's bustling streets, The Tipsy Buccaneer Inn invites with its selection of wine, tobacco, and rum, where talkative pirates gather to share their enthralling escapades.",
    },
    map: {
      x: 610,
      y: 429,
      distanceTo: {
        Bonaire: 0,
        Curacao: DISTSANCES.BONAIRE_CURACAO,
        Panama: DISTSANCES.PANAMA_BONAIRE,
        Barbados: DISTSANCES.BARBADOS_BONAIRE,
        Martinique: DISTSANCES.MARTINIQUE_BONAIRE,
        "St. Eustatius": DISTSANCES.BONAIRE_ST_EUSTATIUS,
        "St. Martin": DISTSANCES.BONAIRE_ST_MARTIN,
        "San Juan": DISTSANCES.SAN_JUAN_BONAIRE,
        Tortuga: DISTSANCES.TORTUGA_BONAIRE,
        Leogane: DISTSANCES.LEOGANE_BONAIRE,
        "Port Royale": DISTSANCES.PORT_ROYALE_BONAIRE,
        Belize: DISTSANCES.BELIZE_BONAIRE,
        "Villa Hermosa": DISTSANCES.VILLA_HERMOSA_BONAIRE,
        Biloxi: DISTSANCES.BILOXI_BONAIRE,
        "Charles Towne": DISTSANCES.CHARLES_TOWNE_BONAIRE,
        Havana: DISTSANCES.HAVANA_BONAIRE,
      },
    },
  },
  Curacao: {
    nation: "Holland",
    descriptions: {
      Shop: "Within the town's vibrant center, The Globetrotter's Market charms passersby with its diverse offerings, from nourishing victuals and leather-bound water bottles to healing elixirs, fragrant tobacco, aged rum, delicate porcelain, and an enchanting variety of spices, all evoking the spirit of exploratory journeys and worldly trade.",
      Tavern:
        "Along the waterfront, The Groggy Sailor Alehouse beckons with its enticing wines, tobacco, and rum, while talkative pirates recount their swashbuckling tales in a lively atmosphere.",
    },
    map: {
      x: 558,
      y: 405,
      distanceTo: {
        Curacao: 0,
        Bonaire: DISTSANCES.BONAIRE_CURACAO,
        Panama: DISTSANCES.PANAMA_CURACAO,
        Barbados: DISTSANCES.BARBADOS_CURACAO,
        Martinique: DISTSANCES.MARTINIQUE_CURACAO,
        "St. Eustatius": DISTSANCES.CURACAO_ST_EUSTATIUS,
        "St. Martin": DISTSANCES.CURACAO_ST_MARTIN,
        "San Juan": DISTSANCES.SAN_JUAN_CURACAO,
        Tortuga: DISTSANCES.TORTUGA_CURACAO,
        Leogane: DISTSANCES.LEOGANE_CURACAO,
        "Port Royale": DISTSANCES.PORT_ROYALE_CURACAO,
        Belize: DISTSANCES.BELIZE_CURACAO,
        "Villa Hermosa": DISTSANCES.VILLA_HERMOSA_CURACAO,
        Biloxi: DISTSANCES.BILOXI_CURACAO,
        "Charles Towne": DISTSANCES.CHARLES_TOWNE_CURACAO,
        Havana: DISTSANCES.HAVANA_CURACAO,
      },
    },
  },
  "St. Martin": {
    nation: "Holland",
    descriptions: {
      Shop: "In the heart of the bustling market, The Merchant's Oasis allures with its eclectic array, housing nourishing provisions and leather-clad water bottles, medicinal remedies, aromatic tobacco, aged rum, delicate porcelain, and a captivating blend of spices, capturing the essence of adventurous expeditions and cross-cultural exchange.",
      Tavern:
        "The Black Pearl Tavern stands tall, offering a variety of wine, tobacco, and rum, where talkative pirates fill the air with animated stories of their daring exploits.",
    },
    map: {
      x: 720,
      y: 301,
      textAlign: "right",
      distanceTo: {
        "St. Martin": 0,
        "St. Eustatius": DISTSANCES.ST_MARTIN_ST_EUSTATIUS,
        Martinique: DISTSANCES.MARTINIQUE_ST_MARTIN,
        Barbados: DISTSANCES.BARBADOS_ST_MARTIN,
        "San Juan": DISTSANCES.SAN_JUAN_ST_MARTIN,
        Tortuga: DISTSANCES.TORTUGA_ST_MARTIN,
        Leogane: DISTSANCES.LEOGANE_ST_MARTIN,
        "Port Royale": DISTSANCES.PORT_ROYALE_ST_MARTIN,
        Biloxi: DISTSANCES.BILOXI_ST_MARTIN,
        "Charles Towne": DISTSANCES.CHARLES_TOWNE_ST_MARTIN,
        Havana: DISTSANCES.HAVANA_ST_MARTIN,
        Belize: DISTSANCES.BELIZE_ST_MARTIN,
        "Villa Hermosa": DISTSANCES.VILLA_HERMOSA_ST_MARTIN,
        Panama: DISTSANCES.PANAMA_ST_MARTIN,
        Curacao: DISTSANCES.CURACAO_ST_MARTIN,
        Bonaire: DISTSANCES.BONAIRE_ST_MARTIN,
      },
    },
  },
  "St. Eustatius": {
    nation: "Holland",
    descriptions: {
      Shop: "Amidst the cobblestone alleys, The Voyager's Trove calls out with its diverse assortment, offering nourishing victuals and leather-bound water bottles, medicinal tinctures, fragrant tobacco, aged rum, delicate porcelain, and an alluring medley of spices, evoking a sense of maritime discoveries and global commerce.",
      Tavern:
        "Tucked away in the old town's hidden corner, The Merry Marauder Tavern serves up wine, tobacco, and rum, while talkative pirates regale each other and curious visitors with thrilling accounts of their adventures.",
    },
    map: {
      x: 741,
      y: 327,
      textAlign: "right",
      distanceTo: {
        "St. Eustatius": 0,
        "St. Martin": DISTSANCES.ST_MARTIN_ST_EUSTATIUS,
        Martinique: DISTSANCES.MARTINIQUE_ST_EUSTATIUS,
        "San Juan": DISTSANCES.SAN_JUAN_ST_EUSTATIUS,
        Barbados: DISTSANCES.BARBADOS_ST_EUSTATIUS,
        Tortuga: DISTSANCES.TORTUGA_ST_EUSTATIUS,
        Leogane: DISTSANCES.LEOGANE_ST_EUSTATIUS,
        "Port Royale": DISTSANCES.PORT_ROYALE_ST_EUSTATIUS,
        Biloxi: DISTSANCES.BILOXI_ST_EUSTATIUS,
        "Charles Towne": DISTSANCES.CHARLES_TOWNE_ST_EUSTATIUS,
        Havana: DISTSANCES.HAVANA_ST_EUSTATIUS,
        Belize: DISTSANCES.BELIZE_ST_EUSTATIUS,
        "Villa Hermosa": DISTSANCES.VILLA_HERMOSA_ST_EUSTATIUS,
        Panama: DISTSANCES.PANAMA_ST_EUSTATIUS,
        Curacao: DISTSANCES.CURACAO_ST_EUSTATIUS,
        Bonaire: DISTSANCES.BONAIRE_ST_EUSTATIUS,
      },
    },
  },
}
