type Town =
  | "Charles Towne"
  | "Belize"
  | "Port Royale"
  | "Barbados"
  | "Martinique"
  | "Biloxi"
  | "Tortuga"
  | "Leogane"
  | "Curacao"
  | "St. Eustatius"
  | "Bonaire"
  | "St. Martin"
  | "Panama"
  | "San Juan"
  | "Havana"
  | "Villa Hermosa"
