const names = [
  "Abominable",
  "Acacia Saint",
  "Acapulco Gold",
  "Acuario",
  "Acuarious",
  "Adios Mamita",
  "Affluential",
  "Afrodita",
  "Aga-Pito",
  "Alimony",
  "Alison",
  "Alpine",
  "Anchors Astray",
  "Anchovia",
  "Angel Of The Sea",
  "Anthony",
  "Aphrodesia",
  "Apocalypso",
  "April Rose",
  "Apta Julia",
  "Aqua Pulp",
  "Aquadisiac",
  "Aquatic Dream",
  "Aracataca",
  "Ariel",
  "Arotiaka",
  "Baba Rum",
  "Baby Nate",
  "Bad Dog",
  "Bail Out",
  "Balmy Steve",
  "Banana Cabana",
  "Bare Necessity",
  "Bay Voyage",
  "Baysick Living",
  "Bella Luna",
  "Bella Vita",
  "Beluga Belt",
  "Bitter Plaid",
  "Black Velvet",
  "Bland Diego",
  "Bleu Et Blanc",
  "Blind Fury",
  "Bloat",
  "Blue Horizon",
  "Blue Sea",
  "Blue Sky",
  "Bluewater",
  "Boil Head",
  "Boilcat",
  "Bolero",
  "Bolt Colt",
  "Bonefly",
  "Boozer",
  "Bottom Checker",
  "Bountyhunter",
  "Brain Mantis",
  "Breakin Wind",
  "Bull Fish",
  "Cabin Fever",
  "Candela",
  "Caribbean King",
  "Caribbean Queen",
  "Caribbean Soul",
  "Carrasco's Melody",
  "Casa Aqua",
  "Cast Away",
  "Celine",
  "Chancaca",
  "Cielo Mio",
  "Cinderella",
  "Clover Deuce",
  "Coco Loco",
  "Constantinople",
  "Continent",
  "Coral Fixation",
  "Coral Reef",
  "Coral Sea",
  "Corsica",
  "Crabby Lady",
  "Crabkitten",
  "Crack Of Dawn",
  "Crescendo",
  "Crimea River",
  "Curious Girl",
  "Current Affair",
  "Current One",
  "Cut-Out",
  "Dancing Girl",
  "Dawn's Early Light",
  "Day Tripper",
  "Debt Setter",
  "Deep Blue",
  "Defacto Princess",
  "Del Mar Dinghy",
  "Deucebra",
  "Dew Mi Moor",
  "Dialogue",
  "Diamantra",
  "Diamond Sky",
  "Dirty Larah",
  "Don Quixote",
  "Doña Flor",
  "Dos Winos",
  "Double Felix",
  "Dredgery",
  "Drippin' Wet",
  "Drippy Dockside",
  "Drunk Fathom",
  "Dulce Miel",
  "Dulcinea",
  "Earthmark",
  "East north",
  "Easy Boy",
  "Easy Girl",
  "Easy Livin'",
  "Eclipse",
  "Eclipto",
  "Elixir",
  "Empty Nest",
  "Endeavor",
  "Endless Summer",
  "Ensure Angler",
  "Eres Mi Loba",
  "Ergoknot",
  "Extro",
  "Fair Weather",
  "Fanarina",
  "Fangold",
  "Fantasea",
  "Fantasy",
  "Far East",
  "Farolito",
  "Faux Phox",
  "Fiasco",
  "Final Curtin",
  "Final Offer",
  "Finale",
  "Fish Eye",
  "Fish Tank",
  "Fishy Business",
  "Five O'clock Shadow",
  "Flagrant Fish",
  "Flamenco",
  "Flight Risk",
  "Fly Bye",
  "Flying Marsius",
  "Flying Monk",
  "Flying Potato",
  "Fo Lita",
  "Fog Blob",
  "Foolish",
  "Foxy Girl",
  "Fragrant",
  "Fraid Knot",
  "Free Bird",
  "Free Spirit",
  "French Girl",
  "Friendly Fire",
  "Frolique",
  "Fruity",
  "Full Throttle",
  "Fully Engaged",
  "Fury",
  "Futitus",
  "Fuzzy Logic",
  "Gaucho Del Mar",
  "Genie's Dream",
  "Giant Path",
  "Giggling Marlin",
  "Gizord",
  "Gloat",
  "Glorious Escape",
  "Goin' Broke",
  "Golden Bass",
  "Golden Meanie",
  "Gone Away",
  "Gone With The Wind",
  "Good Thing",
  "Gorad",
  "Got My Way",
  "Grand Scale",
  "Green Eyed Larry",
  "Green Louie",
  "Greenspan",
  "Half-A-Wake",
  "Hana-Hana",
  "Hang Loose",
  "Happenstance",
  "Happy Times",
  "Harm's Way",
  "Harmony Sea",
  "Heat Wave",
  "Hide Away",
  "High Coup",
  "High Seas Postal",
  "Hog Fog",
  "Hole Hog",
  "Homeless Mistress",
  "Horizon Sky",
  "Horizon Unlimited",
  "Horrid Crab",
  "Huge Attitude",
  "Hungry Beaver",
  "Hurricane",
  "Ice Bear",
  "Idealis",
  "Impossible Dream",
  "Impulse",
  "Inspector",
  "Intrepid Sludge",
  "Iron Arm",
  "Island Rhythm",
  "Isle Rider",
  "Jalapeño Fireball",
  "Jane Belle",
  "Joanna",
  "Join Venture",
  "Jolin-Jolan",
  "Judgment Day",
  "Just Right",
  "Kane Mutiny",
  "Karen Knot",
  "Kelp Monster",
  "King Of The Deeps",
  "King Of The Ocean",
  "King Of The Sea",
  "Kist My Stearn",
  "Kiti-Kiti",
  "Kiwi Kiwi",
  "Knight Of The Sea",
  "Knot Small",
  "Knot So Fast",
  "Knot Too Shabby",
  "Krill",
  "La Bolita",
  "La Consentida",
  "La Morena",
  "La Número Cien",
  "La Zilla",
  "Ladies First",
  "Lafayette",
  "Lagoon",
  "Lake Lizzard",
  "Lake Show",
  "Land Ho",
  "Landphobic",
  "Last Fling",
  "Last Gasp",
  "Lattitude",
  "Laura",
  "Lay A Wake",
  "Lazy Bones",
  "Lazy Boy",
  "Lazy Dazy",
  "Le Jeune Way",
  "Le Manoir",
  "Le Musée",
  "Le Samoa",
  "Le Savoir",
  "Le Victoria",
  "Lee's Ferry",
  "Les Caraibes",
  "Les Delices",
  "Les Passions",
  "Lick The Toad",
  "Liquid Paradise",
  "Lirolai",
  "Loop Hole",
  "Loopy Tuna",
  "Lost Bait",
  "Lost Paradise",
  "Low Ball",
  "Low Tides",
  "Lucitania",
  "Lucitano",
  "Lunamar",
  "Magma Radiant",
  "Magnetic Cocoon",
  "Magnina",
  "Mañana",
  "Mangelica",
  "Mantis",
  "Maravilla",
  "Maria Del Cielo",
  "Maria Del Mar",
  "Mariela",
  "Maringue",
  "Mariposa",
  "Maritza",
  "Mary Of The Sea",
  "Matilde",
  "Medulla Mortadella",
  "Mefistofeles",
  "Melani",
  "Melody",
  "Mindingo",
  "Minga",
  "Miss Charm",
  "Moon River",
  "Morgan",
  "Muñeca Brava",
  "Mystique",
  "Natural Silence",
  "Nature's Wrath",
  "Neversink",
  "New Start",
  "Ocean Dancer",
  "Ocean Debt",
  "Ocean Flower",
  "Ocean Reef",
  "Ocean Stories",
  "Oceanary Soul",
  "Oceanary",
  "Oceanica",
  "Octopus Wrecks",
  "Off The Hook",
  "Old As Dirt",
  "Omega To Epsilon",
  "Opt-Inn",
  "Orion",
  "Oshia",
  "Osmosis",
  "Over The Horizon",
  "Parlame D'amore",
  "Peril",
  "Phaedra",
  "Pineapple Day",
  "Plankwalker",
  "Portogalo",
  "Ports O' Call Tawny",
  "Positive Lattitude",
  "Positive Persuasion",
  "Pour Votre Confort",
  "Prawn God",
  "Prawn Song",
  "Prelude",
  "Pride",
  "Prophet",
  "Proud Mary",
  "Purple Heart",
  "Radiant Fire",
  "Radiant Swift",
  "Rebel Soul",
  "Relentless",
  "Restless Soul",
  "Romeo Mauve",
  "Row Bust",
  "Royal Lush",
  "Royal Wetting",
  "Salty Nights",
  "Salty Weekend",
  "Saphire Rose",
  "Scape From Land",
  "Scene Serene",
  "Sea Bear",
  "Sea Dragon",
  "Sea Guardian",
  "Sea Hunter",
  "Sea Monkey",
  "Sea Thunder",
  "Season Maker",
  "Señor Serene",
  "Señora Bonita",
  "Sequitur",
  "Serenade",
  "Serpent Tina",
  "Seven Seas",
  "Silver Bass",
  "Silver Fox",
  "Sleeky",
  "Slip Away",
  "Snapper Trapper",
  "Sofie",
  "Solitaire",
  "Stardust",
  "Stella Starboard",
  "Stormandy",
  "Storyeller",
  "Sweet Chariot",
  "Sweet Honey",
  "Symphony",
  "Tail Of The Snail",
  "The Hawk",
  "The Old Way",
  "The Salty Weapon",
  "The Swordfish",
  "Three Suns",
  "ThunderSea",
  "Trophy",
  "Trouble",
  "Utara",
  "Valeria",
  "Veronique",
  "Vintage",
  "Wild Blue Yonder",
  "Wonder Boat",
  "Zuniper",
]

const getShipName = () => names[Math.floor(Math.random() * names.length)]

export default getShipName
